spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.216.110:8848
        namespace: 25fc9471-0059-4f86-874e-87d9ce3ff654
  application:
    name: annotator-third-party

server:
  port: 31000

