spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.216.110:8848
        namespace: 31b8f05d-c37f-4f3c-a470-4e2b210cd683
  application:
    name: annotator-api

server:
  port: 7000

#tmp:
#  location: E:\tmp\exportData.json